### ISSUE TITLE
Lab Report Week 1

### ISSUE THREAD

**Issue by enzohnnn** [michaeLeung/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - To improve clarity, should make use of markdown headers instead of just the bolding text feature.
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read
  - It isn't that your text was difficult to read, but I think you can break up some of these large paragraph chunks and put some examples, code, pictures in between to make it neater. 

Additional comments from your grader:
Well done! Your lab is great, just some small fixes and it will look perfect.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by michaeLeung** [comment]
Hi, thanks for the feedback. What does it mean by the last example counts keystrokes?

**Comment by enzohnnn** [comment]
Hi, nice fixes! I see you included a guestimation of keystrokes. For reference, a keystroke is any press of a button. For example, pressing enter, pressing the up arrow, pressing space, any push of a key is a keystroke. We just wanted students to see how using time-saving techniques can save a lot of keystrokes.
